### ISSUE TITLE
Update Discord.JS

### ISSUE THREAD

**Issue by Jozeevis** [Jozeevis/MTG-Spoilers-Discord-bot#22]
The bot still works on a (very) old version of Discord.JS (12.2.0), but the library is two major versions ahead and has many breaking changes. Upgrade the bot to use the new version instead.

**Comment by angrybacon** [comment]
Thanks for putting that bot out there, I was about to do my own from scratch 🤖

I was trying to test it out on a test server of mine but was unable to make it retrieve messages. I spotted that issue and was wondering whether I could expect it to work still today?

I tried logging messages received but found that the content is empty

```
[13/03/2023 19:39] - {
  "channelID": "someid",
  "deleted": false,
  "id": "someid",
  "type": "DEFAULT",
  "content": "",
  "authorID": "someid",
  "pinned": false,
  "tts": false,
  "nonce": "someid",
  "system": false,
  "embeds": [],
  "attachments": [],
  "createdTimestamp": someid,
  "editedTimestamp": null,
  "webhookID": null,
  "applicationID": null,
  "activity": null,
  "flags": 0,
  "reference": null,
  "guildID": "someid",
  "cleanContent": ""
}
```

Is there something wrong in my setup, or is the bot not compatible anymore?

**Comment by Jozeevis** [comment]
@angrybacon Hey there, thanks for your interest!

The bot should still be able to work, I basically have not worked on it for some years and many things have changed, but I got a version of it up and running for myself some weeks ago so it should theoretically still be possible.

Interesting issue that you _are_ getting messages, but the content is empty. First thing that pops to mind is that Discord changed something in their developer portal that now requires you to enable Message Content Intent for the bot to be able to read the content of messages. You can find this in the Discord Developer Portal, go to My Applications > Your Bot > Bot tab > Privileged Gateway Intents > Message Content Intent and that should be checked ON.

Hope that helps, but if not don't hesitate to ask!

**Comment by angrybacon** [comment]
Ah! That was it thanks, I'll try to keep noise to a minimum here and open new issues if necessary

**Comment by Jozeevis** [comment]
Glad I could help!
