### ISSUE TITLE
Dockerize Setup

### ISSUE THREAD

**Issue by samstiyer** [Jozeevis/MTG-Spoilers-Discord-bot#31]
Hey was wondering if you were interested in running a dockerized setup of this as an alternative for installing and running bare metal.

**Comment by Jozeevis** [comment]
Hi there! That's indeed a good idea as an alternative option for people who are used to working with Docker.

I see you've already added some Docker files in your PR #32, so I'll try to see if I can get it to work with those files locally, and when I do I'll merge your PR and possibly add some steps as an alternative to the current installation in the wiki as well.

Thanks for the idea!

**Comment by Jozeevis** [comment]
Everything seems to be working as expected, so I've merged your PR and added the steps to the wiki.

Once again, thanks for the help!
