### ISSUE TITLE
Add to the Discord app directory

### ISSUE THREAD

**Issue by ComradeColeman** [Jozeevis/MTG-Spoilers-Discord-bot#35]
Hey,

Would it be possible at some point to add the app to directory rather than needing to run it locally?

Thanks either way.

**Comment by Jozeevis** [comment]
Hey there, thanks for the question!

I considered this when making the bot, but honestly it was just a fun little coding project to use in a server between me and my friends, and while I'll gladly support other people using it, I'd rather not be responsible for keeping it maintained and up to date within the Discord app directory. This has only become more true now that I've done very little active development on the project for a couple of years.

That said, the project is under the MIT license, so anybody who is interested in putting it in the app directory and taking the responsibility of maintaining it is of course free to do so! But yeah, I personally am not interested in doing that.

Cheers and have a nice day!
