### ISSUE TITLE
Scryfall API change breaks bot

### ISSUE THREAD

**Issue by Melriken** [Jozeevis/MTG-Spoilers-Discord-bot#37]
https://scryfall.com/blog/category/api

Scryfall updated the API to REQUIRE User-Agent and Accept headers for ALL api requests.

As of yesterday the bot will do nothing but throw errors (expected LIST got ERROR).

**Comment by Melriken** [comment]
I submitted a pull request that fixes this issue, I named the agent "DiscordSpoilerbot1.0" you probably want to name it "MTG-Spoilers-Discord-bot-#.#" or something.

**Comment by Jozeevis** [comment]
Thanks a lot for bringing this to my attention, I hadn't noticed it yet!
Probably would've been quite the headache figuring out what was going wrong otherwise.

I'll accept your PR and rename the agent, but thanks again for your help!

**Comment by Jozeevis** [comment]
Accepted the PR, changed the agent and created a new release for this fixed version.
Thanks again for the help!
Closing the issue.
